
var testMeasures = [
    { value: 10, unit:"millimeters", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"inchesdecimal", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"inches", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"points", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"american_points", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"agates", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"bai", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"cm", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"ciceros", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"custom", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"ha", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"mils", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"picas", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"pixels", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"q", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]},
    { value: 10, unit:"u", roundDec:6, convertedValues : [
        { value: 0, unit: "millimeters" },
        { value: 0, unit: "inchesdecimal" },
        { value: 0, unit: "inches" },
        { value: 0, unit: "points" },
        { value: 0, unit: "american_points" },
        { value: 0, unit: "agates" },
        { value: 0, unit: "bai" },
        { value: 0, unit: "cm" },
        { value: 0, unit: "ciceros" },
        { value: 0, unit: "custom" },
        { value: 0, unit: "ha" },
        { value: 0, unit: "mils" },
        { value: 0, unit: "picas" },
        { value: 0, unit: "pixels" }, //@300
        { value: 0, unit: "q" },
        { value: 0, unit: "u" }
    ]}
];
